package cz.jan.maly.model.bot;

import cz.jan.maly.model.features.FeatureContainerHeader;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;

import static cz.jan.maly.model.bot.FactConverters.*;

/**
 * Enumeration of all feature container headers as static classes
 * Created by Jan on 22-Apr-17.
 */
public class FeatureContainerHeaders {

    //ECO manager
    public static final FeatureContainerHeader BUILDING_EXTRACTOR = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefs(new HashSet<>(Collections.singleton(COUNT_OF_WORKERS)))
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES, OPPONENTS_RACE)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS, SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG,
                    SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP, SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS,
                    SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG, SUM_OF_ENEMY_STATIC_AIR_UNITS,
                    SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS, SUM_OF_OWN_AIR_DMG,
                    SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG, SUM_OF_OWN_STATIC_GROUND_DMG,
                    SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS, SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader INCREASING_CAPACITY = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(SUM_OF_ENEMY_AIR_DMG,
                    SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP, SUM_OF_ENEMY_AIR_SHIELDS,
                    SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG, SUM_OF_ENEMY_STATIC_AIR_UNITS,
                    SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS, SUM_OF_OWN_AIR_DMG,
                    SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG, SUM_OF_OWN_STATIC_GROUND_DMG,
                    SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS, SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader TRAINING_WORKER = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefs(new HashSet<>(Collections.singleton(COUNT_OF_WORKERS)))
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES, OPPONENTS_RACE)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader EXPANDING = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefs(new HashSet<>(Collections.singleton(COUNT_OF_WORKERS)))
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();

    //Build order manager
    public static final FeatureContainerHeader BUILDING_POOL = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefs(new HashSet<>(Collections.singleton(COUNT_OF_WORKERS)))
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES, COUNT_OF_ENEMY_BASES,
                    MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader UPGRADING_TO_LAIR = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader BUILDING_SPIRE = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader BUILDING_HYDRALISK_DEN = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader BUILDING_EVOLUTION_CHAMBER = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE, COUNT_OF_EXTRACTORS,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();

    //Unit order manager
    public static final FeatureContainerHeader BOOSTING_AIR = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader BOOSTING_GROUND_MELEE = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();
    public static final FeatureContainerHeader BOOSTING_GROUND_RANGED = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES, CURRENT_POPULATION, MAX_POPULATION)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(AVERAGE_COUNT_OF_WORKERS_PER_BASE,
                    AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE, AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
                    SUM_OF_ENEMY_AIR_DMG, SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP,
                    SUM_OF_ENEMY_AIR_SHIELDS, SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .build();

    //BASE
    public static final FeatureContainerHeader HOLDING = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(SUM_OF_ENEMY_AIR_DMG,
                    SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP, SUM_OF_ENEMY_AIR_SHIELDS,
                    SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .convertersForFactSets(new HashSet<>(Arrays.asList(SUM_OF_ENEMY_AIR_DMG_BASE,
                    SUM_OF_ENEMY_GROUND_DMG_BASE, SUM_OF_ENEMY_AIR_HP_BASE, SUM_OF_ENEMY_GROUND_HP_BASE, SUM_OF_ENEMY_AIR_SHIELDS_BASE,
                    SUM_OF_ENEMY_GROUND_SHIELDS_BASE, SUM_OF_ENEMY_STATIC_AIR_DMG_BASE, SUM_OF_ENEMY_STATIC_GROUND_DMG_BASE,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS_BASE, SUM_OF_ENEMY_STATIC_GROUND_UNITS_BASE, SUM_OF_ENEMY_AIR_UNITS_BASE, SUM_OF_ENEMY_GROUND_UNITS_BASE,
                    SUM_OF_OWN_AIR_DMG_BASE, SUM_OF_OWN_GROUND_DMG_BASE, SUM_OF_OWN_AIR_HP_BASE, SUM_OF_OWN_GROUND_HP_BASE, SUM_OF_OWN_STATIC_AIR_DMG_BASE,
                    SUM_OF_OWN_STATIC_GROUND_DMG_BASE, SUM_OF_OWN_STATIC_AIR_UNITS_BASE, SUM_OF_OWN_STATIC_GROUND_UNITS_BASE, SUM_OF_OWN_AIR_UNITS_BASE,
                    SUM_OF_OWN_GROUND_UNITS_BASE)))
            .convertersForFacts(new HashSet<>(Arrays.asList(IS_BASE, IS_ENEMY_BASE, IS_MINERAL_ONLY, IS_ISLAND, IS_START_LOCATION)))
            .build();
    public static final FeatureContainerHeader DEFENSE = FeatureContainerHeader.builder()
            .convertersForFactsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(COUNT_OF_BASES,
                    COUNT_OF_ENEMY_BASES, MAP_SIZE, OPPONENTS_RACE, AVAILABLE_BASES)))
            .convertersForFactSetsForGlobalBeliefsByAgentType(new HashSet<>(Arrays.asList(SUM_OF_ENEMY_AIR_DMG,
                    SUM_OF_ENEMY_GROUND_DMG, SUM_OF_ENEMY_AIR_HP, SUM_OF_ENEMY_GROUND_HP, SUM_OF_ENEMY_AIR_SHIELDS,
                    SUM_OF_ENEMY_GROUND_SHIELDS, SUM_OF_ENEMY_STATIC_AIR_DMG, SUM_OF_ENEMY_STATIC_GROUND_DMG,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS, SUM_OF_ENEMY_STATIC_GROUND_UNITS, SUM_OF_ENEMY_AIR_UNITS, SUM_OF_ENEMY_GROUND_UNITS,
                    SUM_OF_OWN_AIR_DMG, SUM_OF_OWN_GROUND_DMG, SUM_OF_OWN_AIR_HP, SUM_OF_OWN_GROUND_HP, SUM_OF_OWN_STATIC_AIR_DMG,
                    SUM_OF_OWN_STATIC_GROUND_DMG, SUM_OF_OWN_STATIC_AIR_UNITS, SUM_OF_OWN_STATIC_GROUND_UNITS, SUM_OF_OWN_AIR_UNITS,
                    SUM_OF_OWN_GROUND_UNITS)))
            .convertersForFactSets(new HashSet<>(Arrays.asList(SUM_OF_ENEMY_AIR_DMG_BASE,
                    SUM_OF_ENEMY_GROUND_DMG_BASE, SUM_OF_ENEMY_AIR_HP_BASE, SUM_OF_ENEMY_GROUND_HP_BASE, SUM_OF_ENEMY_AIR_SHIELDS_BASE,
                    SUM_OF_ENEMY_GROUND_SHIELDS_BASE, SUM_OF_ENEMY_STATIC_AIR_DMG_BASE, SUM_OF_ENEMY_STATIC_GROUND_DMG_BASE,
                    SUM_OF_ENEMY_STATIC_AIR_UNITS_BASE, SUM_OF_ENEMY_STATIC_GROUND_UNITS_BASE, SUM_OF_ENEMY_AIR_UNITS_BASE, SUM_OF_ENEMY_GROUND_UNITS_BASE,
                    SUM_OF_OWN_AIR_DMG_BASE, SUM_OF_OWN_GROUND_DMG_BASE, SUM_OF_OWN_AIR_HP_BASE, SUM_OF_OWN_GROUND_HP_BASE, SUM_OF_OWN_STATIC_AIR_DMG_BASE,
                    SUM_OF_OWN_STATIC_GROUND_DMG_BASE, SUM_OF_OWN_STATIC_AIR_UNITS_BASE, SUM_OF_OWN_STATIC_GROUND_UNITS_BASE, SUM_OF_OWN_AIR_UNITS_BASE,
                    SUM_OF_OWN_GROUND_UNITS_BASE, COUNT_OF_CREEP_COLONIES_AT_BASE, COUNT_OF_SPORE_COLONIES_AT_BASE, COUNT_OF_SUNKEN_COLONIES_AT_BASE)))
            .convertersForFacts(new HashSet<>(Arrays.asList(IS_BASE, IS_ENEMY_BASE, IS_MINERAL_ONLY, IS_ISLAND, IS_START_LOCATION)))
            .build();

}
